# Generated by Django 4.2.2 on 2023-06-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_forma_pago',
            fields=[
                ('forma_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago_nombre', models.CharField(max_length=45)),
                ('forma_pago_referencia', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movilidad',
            fields=[
                ('movilidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_tipo_servicio', models.CharField(max_length=45)),
                ('movilidad_turno', models.CharField(max_length=45)),
                ('movilidad_seccion', models.CharField(max_length=45)),
                ('movilidad_docente', models.CharField(max_length=255)),
                ('movilidad_pago', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movilidad_pago',
            fields=[
                ('movilidad_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_pago_fecha', models.DateField()),
                ('movilidad_pago_monto', models.FloatField(default=0)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.tbl_forma_pago')),
                ('movilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.tbl_movilidad')),
            ],
        ),
    ]
